"""The spec pack: the whole language in one file, for a model to read.

Nothing tells a model how to write Scenet, and nothing will from training -- a niche
language is not in anybody's weights, and pretending otherwise wastes effort. What
works for every new library is the same thing: one self-contained document a model can
be handed. This is that document, generated by `scripts/build_spec.py` from the
language reference, the shot-type table, the comic-script guide, the puppet library,
the diagnostic rule catalogue, the published JSON Schema and the whole gallery.

It ships inside the package because the MCP server's `get_spec` tool serves it, and an
installed wheel cannot read `docs/`. A test regenerates it and compares, so the copy
here cannot go stale.

The pack is split into named parts, each opened by a marker comment, so a client that
can ask for one part at a time -- a tool call, an agent skill -- need not pay for the
other seven:

    <!-- scenet-spec:part=language -->
"""

from functools import cache
from importlib.resources import files

__all__ = ["MARKER", "SPEC_PARTS", "part", "spec_pack_text"]

#: Every part of the pack, in order, with what it is for. The descriptions are what a
#: model sees when choosing which part to read, so they say what is *in* each one.
SPEC_PARTS: dict[str, str] = {
    "preamble": (
        "Start here: what Scenet is, the two ways to write a panel, the check-and-fix "
        "loop, and the mistakes generators make most"
    ),
    "language": "The language reference: every block and key of a panel or scene document",
    "shot-types": "Normative: what each camera shot frames, in head-heights",
    "comic-script": "The comic-script format: PANEL 1, @shot:, character cues, dialogue",
    "characters": "The shipped puppets, with every pose and expression each declares",
    "diagnostics": "Every rule `scenet check` reports, and what to do about each",
    "schema": "The JSON Schema for a single-panel YAML document",
    "gallery": "Every gallery example in full, each known to compile",
}

#: The comment that opens each part. One per part, on a line of its own.
MARKER = "<!-- scenet-spec:part={name} -->"

#: Where the generated pack lives inside the package.
RESOURCE = "scenet-spec.md"


@cache
def spec_pack_text() -> str:
    """The whole pack, exactly as published at `/scenet-spec.md` on the documentation site.

    Returns:
        The Markdown text, read once and cached.

    Example:
        >>> from scenet.spec_pack import spec_pack_text
        >>> "<!-- scenet-spec:part=language -->" in spec_pack_text()
        True
    """
    return files("scenet").joinpath(RESOURCE).read_text(encoding="utf-8")


def part(name: str) -> str:
    """One part of the pack, without its marker.

    Args:
        name: A key of :data:`SPEC_PARTS <scenet.spec_pack.SPEC_PARTS>`.

    Returns:
        The part's Markdown, from the line after its marker up to the next marker.

    Raises:
        KeyError: There is no part by that name. The message lists the ones there are.

    Example:
        >>> from scenet.spec_pack import part
        >>> part("comic-script").lstrip().startswith("# Write a panel as a comic script")
        True
    """
    if name not in SPEC_PARTS:
        raise KeyError(f"the spec pack has no part '{name}'; it has {list(SPEC_PARTS)}")
    text = spec_pack_text()
    opening = MARKER.format(name=name) + "\n"
    start = text.index(opening) + len(opening)
    end = text.find("<!-- scenet-spec:part=", start)
    return text[start:] if end == -1 else text[start:end]
