"""The AI-generation disclosure must appear on every published surface.

This project is deliberately almost entirely AI-generated, and says so. That statement
is a requirement rather than a courtesy: anyone who finds this package on PyPI, installs
the extension, or opens the playground is entitled to know what they are looking at
before they decide to rely on it.

It is tested rather than trusted because it is exactly the kind of thing that quietly
disappears -- somebody rewrites a description, trims a README, restructures a page, and
the disclosure goes with it. Nobody notices, because nothing was watching.

Each surface below is a place a stranger can encounter this project without having read
anything else.
"""

import json
from pathlib import Path

import pytest

ROOT = Path(__file__).parent.parent

#: Phrases that, together, constitute the disclosure. A surface must carry at least one
#: -- the wording is adapted to the space available, but the claim is the same.
MARKERS = (
    "deliberately AI-generated",
    "almost entirely generated by AI",
    "almost entirely AI-generated",
    "AI-generated",
)

#: Every file a published surface is built from, and what it becomes.
SURFACES = {
    "README.md": "the PyPI project page (readme = README.md) and the GitHub landing page",
    "docs/index.md": "the documentation site home page",
    "playground/index.html": "the browser playground",
    "editor/README.md": "the VS Code extension description, shown before installing",
    "playground/README.md": "anyone reading the playground source",
}


def _text(relative: str) -> str:
    return (ROOT / relative).read_text(encoding="utf-8")


def _has_disclosure(text: str) -> bool:
    return any(marker.lower() in text.lower() for marker in MARKERS)


@pytest.mark.parametrize(("path", "surface"), SURFACES.items(), ids=list(SURFACES))
def test_surface_carries_the_disclosure(path: str, surface: str):
    assert _has_disclosure(_text(path)), f"{path} becomes {surface}, and must disclose"


class TestPyPI:
    """The package page is the one a stranger is most likely to land on first."""

    def test_the_readme_is_the_long_description(self):
        """If this stops being true, the disclosure stops reaching PyPI."""
        assert 'readme = "README.md"' in _text("pyproject.toml")

    def test_the_disclosure_is_near_the_top(self):
        """Buried at the bottom of a long README, it may as well not be there."""
        lines = _text("README.md").splitlines()
        position = next(index for index, line in enumerate(lines) if _has_disclosure(line))
        assert position < 12, f"disclosure is at line {position + 1}; it belongs above the fold"

    def test_it_is_a_heading_not_a_footnote(self):
        assert any(
            line.startswith("#") and _has_disclosure(line)
            for line in _text("README.md").splitlines()
        )


class TestVSCodeExtension:
    """The marketplace description is shown before anyone reads the README."""

    def test_the_manifest_description_discloses(self):
        manifest = json.loads(_text("editor/package.json"))
        assert _has_disclosure(manifest["description"])


class TestPlayground:
    """A page anyone can reach with one click, and use without reading anything."""

    def test_the_disclosure_is_visible_without_scrolling(self):
        """In the header, not only the footer. A page this tall hides its footer."""
        markup = _text("playground/index.html")
        header = markup[markup.index("<header") : markup.index("</header>")]
        assert _has_disclosure(header)
